orbs:
  node: circleci/node@4.7.0

workflows:
  example-workflow:
    jobs:
      - node/test

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-npm
workflows:
  example-workflow:
    jobs:
      - example-job