version: 2.1
orbs:
  node: circleci/node@4.7.0
publish: &publish
  working_directory: ~/TheLoop
  docker:
    - image: circleci/node:14
  steps:
    - checkout

    - run:
        name: Writing dotenv file
        command: echo "API=${API_URL}" >> .env

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL
        environment:
          NODE_OPTIONS: --max_old_space_size=3999

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/my-app

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: production
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: main
    <<: *publish

  eas_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Trigger build
          command: npx eas-cli build --platform all --non-interactive

workflows:
  node-test:
    jobs:
      - node/run
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: production
      - publish_to_expo_prod:
          filters:
            branches:
              only: main

  build_app:
    jobs:
      - eas_build:
          filters:
            branches:
              only: google_play_automation
# Credit to Josiah for his code in Emotive App.
